### ISSUE TITLE
css.Selector.PseudoDeclaration missing

### ISSUE THREAD

**Issue by whatsdis** [FitLayout/tools#1]
it is nowhere to be found and I've manually copy pasted from https://github.com/radkovo/jStyleParser/tree/7da8502bb525cd6d5a51ce00214206244f15d578/src/main/java/cz

**Comment by radkovo** [comment]
The whole jStyleParser project should be built and installed (`mvn install`) before building FitLayout packages (see FitLayout/Builds#2).
